//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915M_Project_P2
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string TenantID { get; set; }
        public string ShowcaseID { get; set; }
        public string Category { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public int Inventory { get; set; }
        public Nullable<int> NOS { get; set; }
        public string DepartmentID { get; set; }
    }
}
