//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915M_Project_P2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hkcsEntities : DbContext
    {
        public hkcsEntities()
            : base("name=hkcsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> account { get; set; }
        public DbSet<department> department { get; set; }
        public DbSet<inventory> inventory { get; set; }
        public DbSet<item> item { get; set; }
        public DbSet<orders> orders { get; set; }
        public DbSet<rentrecord> rentrecord { get; set; }
        public DbSet<showcaseinfo> showcaseinfo { get; set; }
    }
}
